import assert from 'node:assert/strict';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
const globals = globalThis as unknown as Record<string, unknown>;
globals.localStorage = { getItem: (key: string) => key === 'jx_lang' ? 'zh-CN' : null, setItem() {}, removeItem() {} };
const { ArtifactCardList } = await import('../src/components/chat/ArtifactCardList');
const { useDeploymentModeStore } = await import('../src/stores/deploymentModeStore');
const { registerLocalChat, setHybridDual } = await import('../src/api');
useDeploymentModeStore.setState({ isDesktop: true, provisionMode: 'dual', activeLocal: false });
setHybridDual(true); registerLocalChat('card-local');
const file = { file_id: 'report', name: '周报.pdf', url: '/files/report', chat_id: 'card-local' };
const local = renderToStaticMarkup(React.createElement(ArtifactCardList, { artifacts: [file] }));
assert.match(local, /打开/);
assert.doesNotMatch(local, />下载</);
const cloud = renderToStaticMarkup(React.createElement(ArtifactCardList, { artifacts: [{ ...file, origin: 'cloud' as const }] }));
assert.match(cloud, /下载/);
assert.doesNotMatch(cloud, /打开所在文件夹/);
assert.match(cloud, /href="\/api\/files\/report"/);
console.log('artifact cards: local open/dropdown and cloud download passed');
